a = int(input())     # (1)
b = int(input())     # (2)
c = a * (int(str(b)[2]))     # (3)
d = a * (int(str(b)[1]))     # (4)
e = a * (int(str(b)[0]))     # (5)
print(c)
print(d)
print(e)
print(e * 100 + d * 10 + c)     # (6)